title: git-wiki-demo
description: This is a demo of git-wiki theme for jekyll
show_downloads: true
comments: true
logo_url: https://upload.wikimedia.org/wikipedia/en/thumb/8/80/Wikipedia-logo-v2.svg/1122px-Wikipedia-logo-v2.svg.png
google_analytics:
git_branch: gh-pages
theme: 
use_github_wiki: false
use_prose_io: true
google_cse_token: 007197903287787072094:8rbvkeqo6qw
custom_sidebar: true
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
